version: '3'

services:
  db:
    image: 'mysql:5.7'
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - './db:/docker-entrypoint-initdb.d'
      - './db/data:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=db_app
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password123
    networks:
      - docker-network
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5

  app:
    build: 
      context: ./app
    container_name: app
    networks:
      - docker-network
    volumes:
      - /usr/src/app/node_modules
      - ./app:/usr/src/app
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - docker-network
    depends_on:
      - app

networks:
  docker-network:
    driver: bridge